---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: cluster-monitoring-alertmanager
  labels:
    app.kubernetes.io/component: maas-monitoring
spec:
  groups:
    - name: alertmanager-health
      # note the `job` filter and update accordingly to your setup
      rules:
        - alert: PrometheusAlertmanagerNotificationFailing
          expr: rate(alertmanager_notifications_failed_total[1m]) > 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Prometheus AlertManager notification failing (instance {{ $labels.instance }})
            description: "Alertmanager is failing sending notifications\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
